
GET http://localhost:8080/data/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJucHAiOiI5OTk5OSIsInBhc3N3b3JkIjoiJDJiJDEwJFNMS3hsTVJHVTlvS2xtVFJ0MExnZ3VhNkx0YXBuYUszVjdNNkY4c0ZvclRsVDFqSXFTQkt1IiwiZ3JvdXBfYWtzZXMiOm51bGwsImtvZGVfdW5pdCI6bnVsbCwibmFtYSI6IlJhZmxpU2VwdGlhbmEiLCJrb2RlX2xva2FzaSI6bnVsbCwibnBwX3BlbnVuanVrIjpudWxsLCJrb2RlX2phYmF0YW5fcGVudW5qdWsiOm51bGwsInBlcmlvZGVfbXVsYWlfamFiYXRhbl9zZW1lbnRhcmEiOm51bGwsInBlcmlvZGVfc2VsZXNhaV9qYWJhdGFuX3NlbWVudGFyYSI6bnVsbCwiY3JlYXRlZF9kYXRlIjpudWxsLCJjcmVhdGVkX2J5IjpudWxsLCJtb2RpZmllZF9kYXRlIjpudWxsLCJtb2RpZmllZF9ieSI6bnVsbCwiYWN0aXZlIjpudWxsLCJrb2RlX3Jpd2F5YXRfd2FraWxfc2VtZW50YXJhIjpudWxsLCJzdGF0dXNfd2FraWxfc2VtZW50YXJhIjpudWxsLCJsYXN0X3Nlc3NfaXAiOm51bGwsImtvZGVfbG9rYXNpX3R1Z2FzIjpudWxsLCJrZXkiOm51bGwsInJlZmVyZW5zaV9ucHAiOm51bGwsImlhdCI6MTY2NDM0NjY4NiwiZXhwIjoxNjY0NDMzMDg2fQ.5dHr-3yP7t850Ba8GmQd6sqfOf9ZaRIKZENjZE1XEmM
